"""Simple test to demonstrate tampering detection by modifying client code."""

print("=" * 70)
print("TAMPERING TEST - SIG_FAIL Detection")
print("=" * 70)
print()
print("This test demonstrates that tampering with ciphertext causes")
print("signature verification to fail.")
print()
print("INSTRUCTIONS:")
print("=" * 70)
print()
print("1. Make a backup of app/client.py:")
print("   Copy-Item app\\client.py app\\client.py.backup")
print()
print("2. Open app/client.py and find line ~261 (aes_encrypt_ecb call)")
print()
print("3. Add this code RIGHT AFTER line 261 to flip a bit:")
print()
print("   # TAMPERING TEST: Flip a bit in ciphertext")
print("   ciphertext = bytearray(ciphertext)")
print("   ciphertext[0] ^= 0x01  # Flip first bit")
print("   ciphertext = bytes(ciphertext)")
print()
print("4. Start server: python -m app.server")
print()
print("5. Run client: python -m app.client")
print("   - Login with your credentials")
print("   - Send a message")
print()
print("6. Expected result:")
print("   Server should log: 'ERROR: Signature verification failed'")
print("   Server should send: ErrorMessage {error: 'SIG_FAIL'}")
print()
print("7. Restore backup:")
print("   Copy-Item app\\client.py.backup app\\client.py -Force")
print()
print("=" * 70)
print()
input("Press Enter to see the exact code modification...")

print()
print("EXACT CODE TO ADD (after line 261 in app/client.py):")
print("-" * 70)
print("""
                        # Encrypt plaintext with AES-128
                        plaintext_bytes = plaintext.encode('utf-8')
                        ciphertext = aes_encrypt_ecb(chat_session_key, plaintext_bytes)
                        
                        # TAMPERING TEST: Flip a bit in ciphertext
                        ciphertext = bytearray(ciphertext)
                        ciphertext[0] ^= 0x01  # Flip least significant bit of first byte
                        ciphertext = bytes(ciphertext)
                        
                        ciphertext_b64 = b64e(ciphertext)
""")
print("-" * 70)
print()
print("After adding this code, run the client and send a message.")
print("The server will detect the tampering and reject with SIG_FAIL.")
print()

